### ISSUE TITLE
Client no longer shows sidebar items under macOS 12b3

### ISSUE THREAD

**Issue by tonyarnold** [stacksift/Client#2]
Rebuilding via Xcode shows the items, so I'm not clear on whether this is beta shenanigans, or something else. 

![Stacksift Client showing no sidebar items](https://user-images.githubusercontent.com/4802/126244550-2dd0ab72-9bb4-4fcc-9c34-d95025f525d3.png)

**Comment by mattmassicotte** [comment]
Hmmmm. Thanks for reporting this. Will look into it soon.

**Comment by mattmassicotte** [comment]
Sorry for taking so long to respond to this, but it does look the latest releases of the client and OS no longer exhibit this problem.

**Comment by tonyarnold** [comment]
It's all good - thanks for fixing it, Matt!
